Project modal
Benmuiruri/my-portfolio pull request #17
Opened 2022-03-02 13:44 UTC by Benmuiruri

### Add Project Detail Modal

2022-03-02 17:09 UTC, keroloussamy requested changes
Hi @Benmuiruri 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To highlight 🎯

- No linter errors.✔️
- Good code design and implementation. ✔️

## Required Changes ♻️
_Check the comments under the review._

![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-02 17:09 UTC, keroloussamy commented on index.html
> +                    Test Project
- [ ] Kindly should delete all the projects from HTML and create them by javascript, not only display the modal. As mentioned in the requirements. `You need to update the main page so that the projects section is created dynamically using the information stored in that JavaScript object. Remember, all of the HTML in that section is created when the page loads.`

2022-03-02 17:30 UTC, Benmuiruri commented
Hi @keroloussamy Thanks for the review. As I work on some of the changes you have suggested I have some questions I will ask in the thread of some changes.

2022-03-02 17:33 UTC, Benmuiruri commented on css/style.css
> +}
I am wondering why the buttons are misplaced in your screenshot. Here is how they appear in mine when in desktop version.

![deskmodal](https://user-images.githubusercontent.com/2597305/156415877-bdde4dae-4326-4bb1-a3cf-fa63262f4c8b.png)

Also here is how they look in mobile version (under 992px) 
![mobile modal](https://user-images.githubusercontent.com/2597305/156415912-b2910119-1982-4aed-b360-3a4fbff5df6d.png)

The buttons retain their position upto small windows like 284 as in the image below. 
![small](https://user-images.githubusercontent.com/2597305/156416280-3777801f-e41a-4352-954e-966515df665b.png)

I dont know what might be causing that issue on your side. Any pointers on what I need to change?

2022-03-02 17:42 UTC, Benmuiruri commented on js/main.js
> +  article.id = `project${projects[number].id}`;
I've addressed this. :heavy_check_mark:
![console](https://user-images.githubusercontent.com/2597305/156417612-9f2f05b7-e57c-4836-a5b5-8536e7cd2690.png)

2022-03-02 18:20 UTC, Benmuiruri commented on css/style.css
> +}
I have updated the close button and reduced the image `border-radius` as well :heavy_check_mark:

2022-03-02 18:26 UTC, keroloussamy commented on css/style.css
> +}
@Benmuiruri I have double check on it and still get the same issue with different sizes, you can check it with width more than `950px`

2022-03-02 18:30 UTC, Benmuiruri commented on css/style.css
> +}
@keroloussamy It does remain relatively in the same position. Here is a screenshot at 1500p
![1500](https://user-images.githubusercontent.com/2597305/156425428-984f2a52-d0bf-46ad-93a7-5cdeea97fec9.png)
x

2022-03-02 18:59 UTC, thecodechaser requested changes
## Hi @Benmuiruri 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a title and summary. ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-02 18:59 UTC, thecodechaser commented on css/style.css
> +}
- [ ] As requested by the previous reviewer, Please fix the alignment of the buttons on the pop-up window for desktop screens, It's appearing differently for different screen sizes Please make sure it matches with the Figma design on all screen sizes.

At 1200px

![Screenshot (196)](https://user-images.githubusercontent.com/83803414/156429469-de5c4efd-e9d4-4c59-b46c-60152b4e7866.png)


At 1500px

![Screenshot (197)](https://user-images.githubusercontent.com/83803414/156429445-0aeadf4c-f987-477f-b511-9039f1800d7d.png)


At 1800px

![Screenshot (195)](https://user-images.githubusercontent.com/83803414/156429427-aa4062e6-14ab-4a68-a15d-914c4c6525d2.png)

2022-03-02 19:10 UTC, Benmuiruri commented on css/style.css
> +}
Hi @thecodechaser I think that issue is being caused by using position absolute. Let me try and find another implementation.

2022-03-03 06:17 UTC, Benmuiruri commented on css/style.css
> +}
Hi @thecodechaser thanks for pointing out the issue with the screenshots. I updated the button `CSS` styles. Thanks :pray:

2022-03-03 06:29 UTC, Benmuiruri commented
Thanks for sharing the screenshots the buttons now work as expected. Thanks for the feedback as well.

2022-03-03 06:32 UTC, Kingstalux commented on css/style.css
> +}
Issue addressed 👍

2022-03-03 06:34 UTC, Kingstalux approved these changes
Hi @Benmuiruri , 
# Status: Approved ✔️ ✔️ ✔️ 
![128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c](https://user-images.githubusercontent.com/85113567/156509681-1ec6e4be-3d07-4bd7-80a6-8868aaa747b4.gif)

Good job implementing the required changes 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-03 06:37 UTC, Benmuiruri commented
Thanks for the review everyone involved

2022-03-03 06:38 UTC, merged